[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "flash_moe"
version = "0.0.0"
description = "FlashMoE prototype"
authors = [{name="Vishal Pandey"}]